//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.07 at 09:29:20 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://localhost:8080/post-webservice", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package soap.webservice.consumer.model;
